server:
  address: 0.0.0.0
  port: 2023
  #设置tomcat参数
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  charset:
    console: UTF-8
    file: UTF-8
spring:
  profiles:
    active: local,config
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #thymeleaf模板配置
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    #严格执行H5标准
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  #静态资源路径
  mvc:
    static-path-pattern: /static/**
download: #新增的限速功能
  speed-limit: 1048576  # 1MB/s，单位字节。可修改为其他值如524288（512KB/s）